#ifndef __GETSTATUS_H__
#define __GETSTATUS_H__

#define USE_IDOL_OEM_ENCRYPTION 1
#define IDOL_OEM_ENCRYPTION_KEY_ENV_VAR "ACI_API_TUTORIAL_PROGRAM_ENCRYPTION_KEY"
#define IDOL_OEM_ENCRYPTION_KEY_STUB_VALUE "REPLACE_WITH_MY_LONG_KEY_STRING"
/* When enabling OEM encryption, replace the following value with issued key */
#define IDOL_OEM_ENCRYPTION_KEY IDOL_OEM_ENCRYPTION_KEY_STUB_VALUE

#define EXPECTED_NUM_ARGS (3)

#endif  /*__GETSTATUS_H__*/
