#/bin/sh

VERSION=25.4.0
PLATFORM=LINUX_X86_64

KEYVIEW_FILTERSDK_HOME=/opt/OpenText/KeyviewFilterSDK_${VERSION}_${PLATFORM}
KEYVIEW_EXPORTSDK_HOME=/opt/OpenText/KeyviewExportSDK_${VERSION}_${PLATFORM}
IDOL_OEM_TUTORIALS_HOME=/opt/OpenText/idol-oem-tutorials

KV_SAMPLE_PROGRAM_LICENSE_FROM_FILEPATH=${KEYVIEW_FILTERSDK_HOME}/licensekey.dat
export KV_SAMPLE_PROGRAM_LICENSE_FROM_FILEPATH

PYTHON_EXE=python

INPUT_FILEPATH=${IDOL_OEM_TUTORIALS_HOME}/resources/keyview_filter/2022_calendar_HIDDEN_TEXT.docx
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/Annual_Report.docx
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/freezer2.ppt
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/FreshDinner.doc
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/frshfrozen.xls
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/Investment_Portfolio.xlsx
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/Report_Template.pdf
#INPUT_FILEPATH=${KEYVIEW_EXPORTSDK_HOME}/testdocs/SquaresLetterHead.tiff

METADATA_OUTPUT_FILEPATH=${INPUT_FILEPATH}.KV_${VERSION}_METADATA.TXT
TEXT_OUTPUT_FILEPATH=${INPUT_FILEPATH}.KV_${VERSION}_TEXT.TXT

${PYTHON_EXE} extract_metadata_text.py "${KEYVIEW_FILTERSDK_HOME}/${PLATFORM}/bin" "${INPUT_FILEPATH}" "${METADATA_OUTPUT_FILEPATH}" "${TEXT_OUTPUT_FILEPATH}"
