#ifndef __QUEUEINFO_GETSTATUS_H__
#define __QUEUEINFO_GETSTATUS_H__

#define USE_IDOL_OEM_ENCRYPTION 1
#define IDOL_OEM_ENCRYPTION_KEY_ENV_VAR "ACI_API_TUTORIAL_PROGRAM_ENCRYPTION_KEY"
#define IDOL_OEM_ENCRYPTION_KEY_STUB_VALUE "REPLACE_WITH_MY_LONG_KEY_STRING"
/* When enabling OEM encryption, replace the following value with issued key */
#define IDOL_OEM_ENCRYPTION_KEY IDOL_OEM_ENCRYPTION_KEY_STUB_VALUE

#define EXPECTED_MIN_NUM_ARGS (3+1)
#define EXPECTED_MAX_NUM_ARGS (4+1)

#endif  /*__QUEUEINFO_GETSTATUS_H__*/
