set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_321

set PATH=%JAVA_HOME%\bin;%PATH%

set PROGRAM=EduceRedact
set ACI_HOST=localhost
set ACI_PORT=13000
set MODE=e
set ENTITIES_CSV=REPLACE_WITH_ENTITIES
rem set ENTITIES_CSV=number/cc
set TEXT=REPLACE_WITH_TEXT
rem set TEXT=378282246310005

set ACI_API_TUTORIAL_PROGRAM_ENCRYPTION_KEY=REPLACE_WITH_MY_LONG_KEY_STRING
rem set ACI_API_TUTORIAL_PROGRAM_ENCRYPTION_KEY=

java -jar target/%PROGRAM%-1.0-SNAPSHOT-jar-with-dependencies.jar %MODE% %ACI_HOST% %ACI_PORT% "%ENTITIES_CSV%" "%TEXT%"